version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:1.85.4
    ports:
      - "5678:5678"
    environment:
      # Banco Postgres (use DB_TYPE=postgresdb e variáveis DB_POSTGRESDB_*)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password

      # Segurança básica para acessar o editor (mude usuário/senha)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin_password

      # timezone (opcional)
      - GENERIC_TIMEZONE=America/Sao_Paulo

      # Opcional: aponta para a pasta de custom nodes (padrão já é ~/.n8n/custom)
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom

    volumes:
      - ./data:/home/node/.n8n
    depends_on:
      - postgres
    restart: unless-stopped
